### ISSUE TITLE
How to run GraphSAGE?

### ISSUE THREAD

**Issue by srivas53** [konstantinklemmer/pe-gnn#3]
The Colab code mentions that **"_layers like GAT or GraphSAGE can be used interchangeably with the GCN layers_"**. However, when I replace GCNConv with the SAGEConv function, it throws an index error—debugging shows that the error is in the LossWrapper class of model.py. Please let me know how one can run models like GraphSAGE and GAT.

**Comment by konstantinklemmer** [comment]
Hi @srivas53! I would need to have more details about the error / a way to replicate it. Can you share that?

**Comment by WilliamRappel98** [comment]
Hi @srivas53!
GCNConv and GATConv can be used with the same code, just altering the layer function from GCNConv to GATConv.
However, to apply GraphSAGE using SAGEConv, the only modification needed is to remove the edge_weight argument.

**Comment by konstantinklemmer** [comment]
Yep, what @WilliamRappel98 writes is correct. I will close this issue unless there are further questions.
