### ISSUE TITLE
Problems with function lw_tensor_local_moran

### ISSUE THREAD

**Issue by WilliamRappel98** [konstantinklemmer/pe-gnn#5]
When trying to train with the auxiliary task, the following error appears for the execution of `lw_tensor_local_moran()` function:
**RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.**

Changing the function from:
`zl = torch.tensor(w_sparse * z).to(device)`
  
To:
`zl = torch.tensor(w_sparse * z.detach()).to(device)`
  
  Solved for me.

**Comment by konstantinklemmer** [comment]
`lw_tensor_local_moran(x.detach(), w)` should also work I believe.
